# Generated by Django 5.2.1 on 2025-05-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default='USA', max_length=100),
            preserve_default=False,
        ),
    ]
