# Generated by Django 5.2.1 on 2025-05-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_product_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(default='')),
                ('dataOpened', models.DateField()),
                ('latitute', models.FloatField()),
                ('longitute', models.FloatField()),
            ],
        ),
    ]
