# Generated by Django 5.0 on 2025-07-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_inprogresstask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='nicknamge',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='nickname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
