# Generated by Django 5.2.1 on 2025-07-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_restaurant_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='nicknamge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
