# Generated by Django 5.0 on 2025-06-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('IT', 'Italian'), ('OT', 'Other')], default='Restaurant Type', max_length=2),
            preserve_default=False,
        ),
    ]
