# Generated by Django 5.2.1 on 2025-07-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='objectId',
            new_name='object_id',
        ),
    ]
