# Generated by Django 5.2.1 on 2025-07-03 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_alter_restaurant_options_alter_rating_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.restaurant')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.staff')),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='restaurants',
            field=models.ManyToManyField(through='playground.StaffRestaurant', to='playground.restaurant'),
        ),
    ]
